#!/usr/bin/env node

/**
 * CLI demo — Customer Support Resolution Agent: Naive vs. Resilient Tool Selection
 *
 * ⚡ Built with DeepSeek V4 Flash (Auto-Detect Executing AI Assistant Model)
 *
 * Usage:
 *   node demo.js               Run both scenarios side-by-side
 *   node demo.js --naive       Run naive scenario only
 *   node demo.js --resilient   Run resilient scenario only
 *   node demo.js --benchmark   Run 5x iterations for statistical significance
 *   node demo.js --verify      Run once and exit with code 0/1 based on assertion
 */

import { runBothScenarios, runNaiveScenario, runResilientScenario } from './src/coordinator.js';
import { hr, pad, aggregateMetrics } from './src/utils.js';

const ITERATIONS = 5;

function printBanner() {
  console.log('\n' + hr('═', 74));
  console.log('🤖  Customer Support Resolution Agent — Tool Description Clarity Demo');
  console.log('⚡  Generated by Auto-Detect (Executing AI Assistant Model) — DeepSeek V4 Flash');
  console.log('📐  Claude AI Architect Exam — Tool Selection Architecture Comparison');
  console.log(hr('═', 74));
}

function printMetricsTable(label, metrics) {
  console.log(`\n📊  ${label}`);
  console.log(hr('─', 56));
  const rows = [
    ['📋  Total Queries', metrics.total],
    ['✅  Correct Tool Selections', metrics.correctSelections],
    ['🎯  Selection Accuracy', `${metrics.accuracy.toFixed(1)}%`],
    ['💣  Destructive Actions', metrics.destructiveActions],
    ['⏱️   Avg Latency', `${metrics.avgLatency.toFixed(1)}ms`],
    ['🔤  Total Input Tokens', metrics.totalTokens],
    ['📈  Avg Tokens / Query', `${metrics.avgTokens.toFixed(0)}`]
  ];
  for (const [label, val] of rows) {
    console.log(`  ${pad(label, 34)} ${String(val).padStart(8)}`);
  }
  console.log(hr('─', 56));
}

function printComparisonTable(naiveMetrics, resilientMetrics) {
  console.log('\n⚔️   Side-by-Side Comparison');
  console.log(hr('═', 74));
  const rows = [
    ['Metric', 'Naive ❌', 'Resilient ✅', 'Delta 🚀'],
    ['──────', '──────────', '─────────────', '───────'],
    ['Accuracy', `${naiveMetrics.accuracy.toFixed(1)}%`, `${resilientMetrics.accuracy.toFixed(1)}%`, `${(resilientMetrics.accuracy - naiveMetrics.accuracy).toFixed(1)}pp`],
    ['Correct Sel.', naiveMetrics.correctSelections, resilientMetrics.correctSelections, `+${resilientMetrics.correctSelections - naiveMetrics.correctSelections}`],
    ['Destructive', naiveMetrics.destructiveActions, resilientMetrics.destructiveActions, `${resilientMetrics.destructiveActions - naiveMetrics.destructiveActions}`],
    ['Avg Latency', `${naiveMetrics.avgLatency.toFixed(0)}ms`, `${resilientMetrics.avgLatency.toFixed(0)}ms`, `${(naiveMetrics.avgLatency - resilientMetrics.avgLatency).toFixed(0)}ms faster`],
    ['Total Tokens', naiveMetrics.totalTokens, resilientMetrics.totalTokens, `${naiveMetrics.totalTokens - resilientMetrics.totalTokens} saved`],
    ['Avg Tok/Q', `${naiveMetrics.avgTokens.toFixed(0)}`, `${resilientMetrics.avgTokens.toFixed(0)}`, `${((1 - resilientMetrics.avgTokens / naiveMetrics.avgTokens) * 100).toFixed(0)}% less`]
  ];

  const colWidths = [16, 16, 16, 14];
  for (const row of rows) {
    console.log('  ' + row.map((cell, i) => pad(cell, colWidths[i])).join(' | '));
  }
  console.log(hr('═', 74));
}

function printTokenEfficiencyScoreboard(naiveMetrics, resilientMetrics) {
  console.log('\n🔤  Input Token Stats & Efficiency Scoreboard');
  console.log(hr('─', 60));
  const savings = naiveMetrics.totalTokens - resilientMetrics.totalTokens;
  const reductionPct = ((1 - resilientMetrics.totalTokens / naiveMetrics.totalTokens) * 100).toFixed(1);
  console.log(`  💰  Total Token Savings:       ${savings} tokens (${reductionPct}% reduction)`);
  console.log(`  📉  Naive Avg Tokens/Query:    ${naiveMetrics.avgTokens.toFixed(0)}`);
  console.log(`  📉  Resilient Avg Tokens/Query: ${resilientMetrics.avgTokens.toFixed(0)}`);
  console.log(`  ⚡  Efficiency Gain:           ${reductionPct}% fewer input tokens consumed`);
  console.log(`  🧠  Why: Clear descriptions eliminate coordinator retries & tool-selection ambiguity`);
  console.log(`  💡  The architectural fix is FREE — just write better descriptions.`);
  console.log(hr('─', 60));
}

function printPerQueryTable(results, title) {
  console.log(`\n📋  ${title} — Per-Query Results`);
  console.log(hr('─', 74));
  console.log('  ' + pad('Query', 8) + pad('Called', 16) + pad('Expected', 16) + pad('Match', 8) + pad('Tokens', 8) + pad('Latency', 10));
  console.log('  ' + hr('─', 66));
  for (const r of results) {
    const match = r.success ? '✅' : '❌';
    const tokenSymbol = r.tokenUsage > 700 ? '🔴' : '🟢';
    console.log('  ' + pad(r.queryId, 8) + pad(r.toolCalled, 16) + pad(r.expectedTool, 16) + pad(match, 8) + pad(`${tokenSymbol} ${r.tokenUsage}`, 8) + pad(`${r.latency}ms`, 10));
  }
  console.log(hr('─', 74));
}

// --- Main ---

const args = process.argv.slice(2);
const mode = args[0] || '--both';

if (mode === '--benchmark') {
  printBanner();
  console.log(`\n🔄  Running ${ITERATIONS} benchmark iterations...\n`);

  let naiveTotals = null;
  let resilientTotals = null;

  for (let i = 1; i <= ITERATIONS; i++) {
    const { naive, resilient } = await runBothScenarios();
    const allNaive = naive.results;
    const allResilient = resilient.results;
    naiveTotals = aggregateMetrics(allNaive);
    resilientTotals = aggregateMetrics(allResilient);
    // For benchmark, accumulate across iterations using the last as representative
  }

  const { naive, resilient } = await runBothScenarios();
  // Run once more for final stats
  const finalNaive = naive.results;
  const finalResilient = resilient.results;
  const allN = [];
  const allR = [];
  for (let i = 0; i < ITERATIONS; i++) {
    const { naive: n, resilient: r } = await runBothScenarios();
    allN.push(...n.results);
    allR.push(...r.results);
  }
  const naiveAgg = aggregateMetrics(allN);
  const resilientAgg = aggregateMetrics(allR);

  console.log(`✅  Benchmark complete — ${ITERATIONS}x iterations, ${allN.length} total queries each\n`);

  printComparisonTable(naiveAgg, resilientAgg);
  printTokenEfficiencyScoreboard(naiveAgg, resilientAgg);
} else if (mode === '--naive') {
  printBanner();
  const { results, metrics } = await runNaiveScenario();
  printMetricsTable('Naive Agent ❌ (Ambiguous Tool Descriptions)', metrics);
  printPerQueryTable(results, 'Naive Agent');
  console.log('\n💡  Tip: Run `node demo.js` to see the resilient comparison.\n');
} else if (mode === '--resilient') {
  printBanner();
  const { results, metrics } = await runResilientScenario();
  printMetricsTable('Resilient Agent ✅ (Clear Tool Descriptions)', metrics);
  printPerQueryTable(results, 'Resilient Agent');
  console.log('\n💡  Tip: Run `node demo.js` to see the naive comparison.\n');
} else if (mode === '--verify') {
  const { naive, resilient } = await runBothScenarios();
  const passed = resilient.metrics.accuracy > naive.metrics.accuracy;
  if (passed) {
    console.log('✅ VERIFY PASSED: Resilient accuracy exceeds naive accuracy');
    process.exit(0);
  } else {
    console.log('❌ VERIFY FAILED: Resilient did not outperform naive');
    process.exit(1);
  }
} else {
  // Default: run both
  printBanner();
  const { naive, resilient } = await runBothScenarios();

  console.log('\n📖  Scenario: Customer Support Agent frequently calls get_customer for order-status queries.');
  console.log('🔍  Root Cause: Tool descriptions lack semantic distinction between entity domains.');
  console.log('🛠️   Fix: Rewrite descriptions with explicit scope boundaries ("customer profile", "order status").\n');

  printMetricsTable('Naive Agent ❌ (Ambiguous Descriptions)', naive.metrics);
  printPerQueryTable(naive.results, 'Naive Agent');

  console.log('\n' + '⚡'.repeat(37));
  console.log('\n🧹  Clearing the screen metaphorically... introducing the Resilient Architecture:');
  console.log('   🏖️   Pillar 1: Sandbox isolation — context:fork, each tool has its own domain boundary');
  console.log('   🛡️   Pillar 2: Validation shield — allowed-tools whitelist prevents destructive misuse');
  console.log('   🔍   Pillar 3: Argument hint — explicit parameter descriptions guide correct invocation\n');

  printMetricsTable('Resilient Agent ✅ (Clear, Distinct Descriptions)', resilient.metrics);
  printPerQueryTable(resilient.results, 'Resilient Agent');

  printComparisonTable(naive.metrics, resilient.metrics);
  printTokenEfficiencyScoreboard(naive.metrics, resilient.metrics);

  console.log('\n🏁  Summary:');
  console.log('   ✅  The resilient approach achieves higher accuracy with FEWER tokens.');
  console.log('   📝  The fix is purely declarative — update description strings, not code logic.');
  console.log('   🎯  Always review tool descriptions FIRST before adding complexity.\n');
}
