/**
 * Narration scripts for Web Speech API auto-narrated walkthrough.
 * Each entry contains:
 *   - text: The spoken label (≤7 words per concept — the audio labels, it does not explain)
 *   - selector: CSS selector of the section to scroll to
 *   - durationHint: approximate speaking duration in ms
 *
 * Used by both index.html (GSAP timeline sync) and remotion/src (audio track source).
 *
 * ⚡ Generated by DeepSeek V4 Flash (Auto-Detect Executing AI Assistant Model)
 */

const NARRATION_SCRIPTS = [
  {
    id: 'scene1',
    text: 'Customer Support Agent. Tool Selection Problem.',
    selector: '#scene1-title',
    durationHint: 4000
  },
  {
    id: 'scene2-intro',
    text: 'Naive approach. Wrong tool selected.',
    selector: '#scene2-naive',
    durationHint: 3000
  },
  {
    id: 'scene2-fail',
    text: 'get_customer called. lookup_order needed. Failure.',
    selector: '#scene2-fail',
    durationHint: 5000
  },
  {
    id: 'scene3-intro',
    text: 'Resilient architecture. Three pillars emerge.',
    selector: '#scene3-resilient',
    durationHint: 3000
  },
  {
    id: 'scene3-pillars',
    text: 'Description clarity. Entity boundaries. Correct tool.',
    selector: '#scene3-pillars',
    durationHint: 5000
  },
  {
    id: 'scene3-shield',
    text: 'Shield blocks. Destructive action prevented.',
    selector: '#scene3-shield',
    durationHint: 3000
  },
  {
    id: 'scene4-metrics',
    text: 'Metrics. Token reduction. Accuracy gain.',
    selector: '#scene4-metrics',
    durationHint: 6000
  },
  {
    id: 'scene5-outro',
    text: 'Fix descriptions first. Agent succeeds.',
    selector: '#scene5-outro',
    durationHint: 3000
  },
  {
    id: 'step1-domain',
    text: 'Domain model. Tools and schema entities.',
    selector: '#step1-domain',
    durationHint: 5000
  },
  {
    id: 'step2-cli',
    text: 'CLI comparison. Naive versus resilient output.',
    selector: '#step2-cli',
    durationHint: 5000
  },
  {
    id: 'step4-outro',
    text: 'Token scoreboard. Efficiency savings clear.',
    selector: '#step4-outro',
    durationHint: 4000
  }
];

export default NARRATION_SCRIPTS;
